### ISSUE TITLE
All the clomun value's types of the same when write data to hbase by hbase-rdd？

### ISSUE THREAD

**Issue by TopSpoofer** [unicredit/hbase-rdd#22]
```
sc.textFile("test-input")
    .map({ line =>
      val Array(k, col1, col2, _) = line split "\t"
      val content = Map("col1" -> col1, "col2" -> col2)

      k -> content
    }).toHBase("test-table", "cf1")

```
if the content is Map("col1" -> col1, "col2" -> 1),  so the content type is Map[string, Any], it can't work ?

**Comment by andreaferretti** [comment]
No, it will not work, because you need an implicit `Writes[A]` in scope, for the type `A` of values. Unless you somehow write an instance of `Writes[Any]`, this will not work.

What you can do is convert to some common type that is serializable, for instance a json4s `JValue`, or, at worst, convert everything to `Array[Byte]` yourself (which would happen anyway before writing)

**Comment by TopSpoofer** [comment]
@andreaferretti  I thing so， we can write an instance of Writes[Any] and make it work！
