### ISSUE TITLE
Support for Bulk Deletes?

### ISSUE THREAD

**Issue by poneill00** [unicredit/hbase-rdd#33]
Not sure if this is still being maintained, but is there any way currently to mix PUT & DELETE in a single call to BulkWrite?

**Comment by fralken** [comment]
Hello, can you better explain what's your need? Given a RDD, you can collect records to be written and records to be deleted, and then call a toHBase on the first one, and a deleteHBase on the second one.

**Comment by poneill00** [comment]
Thx for reply.

I'm using the toHBaseBulk function as I'm modifying a large amount of data so pushing via hfile is faster, but I don't see a way to write deletes to the hfiles if I want to delete large about of data?

One other question, since the code currently uses columnId as the key, it means you don't support multiple cell versions, right?
(As they will overwrite each other. Or am I missing something?)

Thanks again!

**Comment by fralken** [comment]
Ok, I understand that you wish to write hfiles with records marked as PUT and record marked as DELETE. Well, this is not implemented.

Multiple cell versions are supported via timestamps. Instead of having `(key, qualifier, value)` you have `(key, qualifier, (value, timestamp))`. I prefer to bind the timestamp to the value (rather than to the cell) to keep the api interfaces of this library more consistent.
You can specify timestamps for writes and deletes.

**Comment by poneill00** [comment]
Ok understood about the deletes.

Regarding the versions, the issue I'm seeing is that I can't return multiple versions since the qualifier is the key in the map. I think you'd need an array of tuples to support multiple versions?

One more question on my use case.
I'm reading all the data from a table with two cf, modifying the value and using bulk to load the data back in.

When my job runs i'm seeing what looks like two reads and then a union before the hfile write and load. Is there anyway to do a single read as I guess this would be better performance? Apologies if this is a stupid question, I'm very new to spark!

Thanks for your replies

**Comment by fralken** [comment]
For reading, only the latest version is returned. I didn't have a use case that required reading all versions of a cell.
For writing, you can write mulitple versions of the same cell.
As for the last question, the actual reading is performed by `newAPIHadoopRDD` of SparkContext. I don't know exactly what happens there.

**Comment by poneill00** [comment]
will the multiple versions for writing not have the same problem?
Since the column qualifier is the key you can't have multiple versions?

The source of the read per cf seems to be the for each cf loop in your bulk write function? This causesa read per c.f. And then a union.
I can't figure out a way to get this to use a single read RDD, I tried cache & checkpoint but no good.
But I'm a complete spark novice...any ideas?

Tix for support

**Comment by poneill00** [comment]
Hey,

So will the two versions be in two separate maps? My understanding was that there was a single map for each cf and a single entry/key for each column? 

I understand why we need the loop for the write, it's just that it seems to cause two reads. Is there a way that a single read can be split between the two writes?

**Comment by fralken** [comment]
Yes the two versions are in separate maps. You can organize maps as you like. You can have one map with one cf and all columns of a rowkey, are have a map for each column of the rowkey (for the same cf). This is because in the end these data structures are deconstructed to a sequence of hbase cells.

Can you point to the code snippet where the two reads are performed? In the "bulk write" code there are no reads from hbase, so I can't understand what you are referring to.

**Comment by poneill00** [comment]
Ah ok, I think I get it regarding the versions.

The bulk code isn't doing the reads but if you do rdd = readTs.doSomething().toBulk() it will cause what looks like two reads.
I tried calling cache or persist before toBulk() but it had no effect.

I think because you call collect() on each cf rdd that the DAG will duplicate the read for each collect?

**Comment by fralken** [comment]
Probably the two reads are because you are reading from two column families, that is, from two different parts of the table. I don't know what to suggest, maybe you can try to partition your rdd in some way before calling 'doSomething()', but not sure this can have any effect.

Your use case is quite peculiar, are you sure HBase is the right tool to solve it? Loading a table by writing hfiles directly is a technique that should be used occasionally. I think it is not intended to bulk load the same table many times.
